# Generated by Django 4.2 on 2024-05-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plan_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.plan'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.user'),
        ),
    ]
