# Generated by Django 4.2 on 2024-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpayment_plan_alter_userpayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
