# Generated by Django 4.2 on 2024-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userpayment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kurs nomi'),
        ),
    ]
