# Generated by Django 4.2 on 2024-05-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userpayment_created_at_userpayment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='plan',
        ),
    ]
