# Generated by Django 4.2 on 2024-07-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_userpayment_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="telegram_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
