# Generated by Django 4.2 on 2024-07-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_plan_telegram_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"verbose_name": "Lectures"},
        ),
        migrations.AlterModelOptions(
            name="userpayment",
            options={"verbose_name": "User Payments"},
        ),
        migrations.AddField(
            model_name="plan",
            name="amount",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
