# Generated by Django 4.2.14 on 2024-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_plan_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="screenshoot",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
