# Generated by Django 4.2.14 on 2024-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userpayment_screenshoot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course name'),
        ),
    ]
